---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  image: ghcr.io/arjunavinfra/sample-app-web
  interval: 1m0s
  secretRef:
    name: regcred
