---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  image: arjunavinfra/sample
  interval: 1m0s
  secretRef:
    name: regcred