apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: application
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./app/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: pandora-compass-helm
      namespace: pandora
  timeout: 1m
