apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: default
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfod
          image: ghcr.io/arjunavinfra/sample-app-web:5.0.1
          imagePullPolicy: IfNotPresent
          imagePullSecrets:
            - name: regcred
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP