---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  image: ghcr.io/arjunavinfra/podinfo
  interval: 2m0s
  # secretRef:
  #   name: regcred
  # timeout: 4m
