apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pandora

resources:
  - namespace.yaml
  - release.yaml


configMapGenerator:
  - name: compass-config
    files:
      - values.yaml=my-values.yaml

# secretGenerator:
#   - name: compass-secret
#     files:
#       - values.yaml=my-values.enc.yaml

configurations:
  - kustomizeconfig.yaml