apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml  
  - pod.yaml

# configMapGenerator:
#   - name: podinfo-values
#     files:
#       - values.yaml=my-values.yaml

# secretGenerator:
#   - name: podinfo-values
#     files:
#       - values.yaml=my-values.enc.yaml

# configurations:
#   - kustomizeconfig.yaml
