apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: compass
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: helm
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: compass
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2