apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIllYSnFkVzVoZG1sdVpuSmhPbWxoYldGeWFuVnVZWFpBTVRJPSIKCQl9Cgl9Cn0=
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIllYSnFkVzVoZG1sdVpuSmhPbWxoYldGeWFuVnVZWFpBTVRJPSIKCQl9Cgl9Cn0=
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson