apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: apps
spec:
  url: http://175.24.198.168:8080
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app
spec:
  chart:
    spec:
      chart: nginx
      version: "13.2.12"
      sourceRef:
        kind: HelmRepository
        name: apps
  values:
    replicas: 6